name: Deploy to deploy branch with include_file

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Linter
        uses: pre-commit/action@v2.0.3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install python dependency
        run: |
          python -m pip install --upgrade pip
          pip install include_file
      - name: Include Files
        run: |
          python -m include_file -u seanhwangg -y SUMMARY.md -d deploy -toc README.md --stem

      - name: Push changes to deploy branch
        uses: EndBug/add-and-commit@v7
        with:
          message: "Committed by seanhwangg/include_file"
          pull_strategy: NO-PULL
          branch: deploy
          push: origin deploy --force -u
